### ISSUE TITLE
Create a directory for tests scripts 

### ISSUE THREAD

**Issue by ArashYzd** [AlbertaSat/ex2_ground_station_software#33]
Currently, there exist a number of test scripts in the /src directory.

- [x] These files contain redundant lines of code that must be captured in a general file. 
- [x] With more test scripts to be created, there is a need for a /test directory. Simply moving the current files to a new path, however, cause errors.
- [x] It'd also be good to have separate directories inside the /test such as /test/uhf as we might be interested in different scripts for different scenarios (TRX disconnected/connected to OBC/radio, HK/Beacon task are operational, etc.). Creating the scripts, however, is not one's responsibility that will handle this issue.

Please refer to the discussions in [this](https://github.com/AlbertaSat/ex2_ground_station_software/pull/18) PR for more info.

**Comment by wagnerd97** [comment]
https://github.com/AlbertaSat/ex2_ground_station_software/pull/40
