### ISSUE TITLE
Add separate time_management subservices for EPS and OBC

### ISSUE THREAD

**Issue by ArashYzd** [AlbertaSat/ex2_ground_station_software#36]
The endianness is different. Right now, the easiest solution is to have separate subservices for get_time and set_time. Remember that EPS's subport numbers are fixed. As a result, changes in ex2_services are required.

**Comment by Taylorr82** [comment]
Why not just have the obc convert the endianess for itself?

**Comment by ArashYzd** [comment]
We technically can, but someone might think of it as a mistake because other obc services are big-endian. We have all these other services/subservices for EPS anyway. What's two more

**Comment by ryankortbeek** [comment]
@ArashYzd is this resolved?

**Comment by ArashYzd** [comment]
Yeah, we have different subservices for them. It's the best way to handle this atm.
