### ISSUE TITLE
Create wiki page for API endpoints

### ISSUE THREAD

**Issue by ryankortbeek** [AlbertaSat/ex2_ground_station_software#47]
### Brief Feature Description
There should be a wiki page documenting the ground station API endpoints.

### Additional Details
It would be really useful if the specifics of API endpoints were documented. It would be valuable to include parameter value info, return value info, and possible exceptions for each endpoint, along with anything else deemed useful.

### Priority
Medium.

**Comment by ryankortbeek** [comment]
@wagnerd97 can you link the housekeeping documentation here once you're done? I can transcribe it over to a wiki page and then we can add documentation for other endpoints onto that as we go.

**Comment by wagnerd97** [comment]
https://docs.google.com/document/d/1omIHK4MzHbxypq8ToDu1dE1muhvdPr7XXRw27XumDH8/edit?usp=sharing

**Comment by ryankortbeek** [comment]
The housekeeping wiki can be found [here](https://github.com/AlbertaSat/ex2_ground_station_software/wiki/Housekeeping)

**Comment by ryankortbeek** [comment]
Other ground station software command documentation can be found [here](https://github.com/AlbertaSat/ex2_ground_station_software/blob/master/CommandDocs.txt).
